stages:
  - build
  - greenlight

build_job:
  image: maven:3.6.0-jdk-8
  stage: build
  script:
    - mvn clean package
  artifacts:
    name: verademo_julian_10_build
    paths:
      - target/
    expire_in: 1 week
  cache:
    paths:
      - target/
      - .m2/repository
    
  
greenlight_job:
  stage: greenlight
  image: openjdk:8-jre
  dependencies:
    - build_job
  artifacts:
    name: verademo_julian_10_greenlight-results
    paths:
      - results.json
      - results.txt
  script:
    - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
    - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
    - java -jar gl-scanner-java.jar
      --api_id "6f66c96112cee650637ebbf6dee3f774"
      --api_secret_key "4072b8357a06e8fc736b5e2139c90b2d9862feab7d4897da1c94ef5f04a72c36525889f45e48bae6c9a1311bd1134aa322d3cf0aba00df02a76bd3f60c7a7bb6"
      --build_dir "target/classes/"
      --source-dir "src/main/java/"
      --issue_details=true
      --summary_output=true
  artifacts:
    name: verademo_julian_10_greenlight-results
    paths:
      - results.json
      - results.txt
    when: always
