stages:
  - build
  - greenlight

build_job:
  stage: build
  script:
    - mvn clean verify
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
    paths:
      - build/
    expire_in: 1 week
  
greenlight_job:
  stage: greenlight
  dependencies:
    - build_job
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_greenlight-results
    paths:
      - results.json
    expire_in: 1 week
    when: always
  script:
    - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
    - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
    - java -jar gl-scanner-java.jar
      --api_id "${VERACODE_API_ID}"
      --api_secret_key "${VERACODE_API_SECRET}"
      --source_dir "src/main/java"
      --build_dir "target/classes"
      --project_name "${CI_PROJECT_NAME}"
      --project_url "${CI_PROJECT_URL}"
      --project_ref "${CI_COMMIT_REF_NAME}"
      --previous_job_name "${CI_JOB_NAME}"
      --gitlab_api_token "${PRIVATE_TOKEN}"