---
image: docker-ro.laputa.veracode.io/agora/buildbox:centos7-m1-java8-latest

stages:
    - build
    - scan

maven:
    stage: build
    script:
        - yum -y install maven
        - mvn compile package
    artifacts:
        paths:
            - target/
          
greenlight scan:
    stage: build
    artifacts:
        name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_greenlight-results
        paths:
            - results.json
        expire_in: 1 day
        when: always
    script:
        - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
        - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
        - java -jar gl-scanner-java.jar
            --api_id 5c0cbad0ad195c9d5ad46f4fb85dbc16
            --api_secret_key b7d27211e0787151f7a215a932b45a64119b4ab96412489309e834e0c5c86dd1ceb3c0583a1ad32c188c362ac2005a8b819e2f2ed9a9765913f4d6bda647fa16
            --project_name "${CI_PROJECT_NAME}"
            --project_url ${CI_PROJECT_URL}
            --project_ref ${CI_COMMIT_REF_NAME}
