stages:
  - build
  - greenlight

build_job:
  stage: build
  script:
    - mvn -X clean verify
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
    paths:
      - build/
    expire_in: 1 week
  
greenlight_job:
  stage: greenlight
  dependencies:
    - build_job
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_greenlight-results
    paths:
      - results.json
    expire_in: 1 week
    when: always
  script:
    - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
    - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
    - java -jar gl-scanner-java.jar
      --api_id "6f66c96112cee650637ebbf6dee3f774"
      --api_secret_key "4072b8357a06e8fc736b5e2139c90b2d9862feab7d4897da1c94ef5f04a72c36525889f45e48bae6c9a1311bd1134aa322d3cf0aba00df02a76bd3f60c7a7bb6"
      --source_dir "src/main/java"
      --build_dir "target/classes"
      --project_name "${CI_PROJECT_NAME}"
      --project_url "${CI_PROJECT_URL}"
      --project_ref "${CI_COMMIT_REF_NAME}"
      --previous_job_name "${CI_JOB_NAME}"
      --gitlab_api_token "${PRIVATE_TOKEN}"